
Epoch 1/1000
aver metric loss-4.055e-03, aver reg loss8.353e-05
Total time 17.573567152023315
Epoch 2/1000
aver metric loss-9.429e-03, aver reg loss2.777e-04
Total time 17.357479095458984
Epoch 3/1000
aver metric loss-1.249e-02, aver reg loss4.171e-04
Total time 16.96280312538147
Epoch 4/1000
aver metric loss-1.442e-02, aver reg loss5.591e-04
Total time 16.931409120559692
Epoch 5/1000
aver metric loss-1.718e-02, aver reg loss7.275e-04
Total time 18.004268884658813
Epoch 6/1000
aver metric loss-3.220e-02, aver reg loss7.804e-04
Total time 17.41544795036316
Epoch 7/1000
aver metric loss-3.599e-02, aver reg loss8.326e-04
Total time 17.248950958251953
Epoch 8/1000
aver metric loss-3.571e-02, aver reg loss9.004e-04
Total time 16.376593589782715
Epoch 9/1000
aver metric loss-3.663e-02, aver reg loss9.930e-04
Total time 17.62116312980652
Epoch 10/1000
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/resource_sharer.py", line 149, in _serve
    send(conn, destination_pid)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/reduction.py", line 179, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/socket.py", line 463, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 412, in _handle_workers
    pool._maintain_pool()
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 248, in _maintain_pool
    self._repopulate_pool()
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    result = Procedure.Test(args, dataset, model, epoch, device, w, args.multicore)
  File "/data1/deepdog/project/GFML/MCL/code/Procedure.py", line 154, in Test
    pre_results = pool.map(test_one_batch, X)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt