2023-07-01 18:27:21 INFO Running runs: []
2023-07-01 18:27:22 INFO Agent received command: run
2023-07-01 18:27:22 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0072035246099281395
2023-07-01 18:27:22 INFO About to run command: --lambd=1 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:27:22 ERROR Exception while processing command: {'run_id': 'bqlfopnc', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY3NjcwNQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmJxbGZvcG5jOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:27:27 INFO Agent received command: run
2023-07-01 18:27:27 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0029254288386224413
2023-07-01 18:27:27 INFO About to run command: --lambd=1 --lr=0.0029254288386224413 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:27:27 ERROR Exception while processing command: {'run_id': 'owczn4eq', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0029254288386224413}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY3NjcxMA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm93Y3puNGVxOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:27:33 INFO Agent received command: run
2023-07-01 18:27:33 INFO Agent starting run with config:
	lambd: 5
	lr: 0.0006905444777069329
2023-07-01 18:27:33 INFO About to run command: --lambd=5 --lr=0.0006905444777069329 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:27:33 ERROR Exception while processing command: {'run_id': 'omof0i63', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 5}, 'lr': {'value': 0.0006905444777069329}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY3NjcxNA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm9tb2YwaTYzOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=5': '--lambd=5'
2023-07-01 18:32:25 INFO Running runs: []
2023-07-01 18:32:26 INFO Agent received command: run
2023-07-01 18:32:26 INFO Agent starting run with config:
	lambd: 1.0
	lr: 0.0072035246099281395
2023-07-01 18:32:26 INFO About to run command: --lambd=1.0 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:32:26 ERROR Exception while processing command: {'run_id': 'ba2gcfp2', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': '1.0'}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY3NzY1MQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmJhMmdjZnAyOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1.0': '--lambd=1.0'
2023-07-01 18:32:32 INFO Agent received command: run
2023-07-01 18:32:32 INFO Agent starting run with config:
	lambd: 5.0
	lr: 0.0012695765699673206
2023-07-01 18:32:32 INFO About to run command: --lambd=5.0 --lr=0.0012695765699673206 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:32:32 ERROR Exception while processing command: {'run_id': '036a54rm', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': '5.0'}, 'lr': {'value': 0.0012695765699673206}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY3NzY3OA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjAzNmE1NHJtOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=5.0': '--lambd=5.0'
2023-07-01 18:44:19 INFO Running runs: []
2023-07-01 18:44:20 INFO Agent received command: run
2023-07-01 18:44:20 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0072035246099281395
2023-07-01 18:44:20 INFO About to run command: --lambd=1 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:44:20 ERROR Exception while processing command: {'run_id': '56ogwzrk', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NDg1Mw==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjU2b2d3enJrOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:44:25 INFO Agent received command: run
2023-07-01 18:44:25 INFO Agent starting run with config:
	lambd: 0.01
	lr: 0.008580823714520389
2023-07-01 18:44:25 INFO About to run command: --lambd=0.01 --lr=0.008580823714520389 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:44:25 ERROR Exception while processing command: {'run_id': '2mjle22n', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 0.01}, 'lr': {'value': 0.008580823714520389}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NDg2MQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjJtamxlMjJuOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=0.01': '--lambd=0.01'
2023-07-01 18:44:31 INFO Agent received command: run
2023-07-01 18:44:31 INFO Agent starting run with config:
	lambd: 5
	lr: 0.002210899454957633
2023-07-01 18:44:31 INFO About to run command: --lambd=5 --lr=0.002210899454957633 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:44:31 ERROR Exception while processing command: {'run_id': '3keeprnh', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 5}, 'lr': {'value': 0.002210899454957633}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NDg2NQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjNrZWVwcm5oOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=5': '--lambd=5'
2023-07-01 18:44:36 INFO Agent received command: run
2023-07-01 18:44:36 INFO Agent starting run with config:
	lambd: 3
	lr: 0.006272310529834396
2023-07-01 18:44:36 INFO About to run command: --lambd=3 --lr=0.006272310529834396 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:44:36 ERROR Exception while processing command: {'run_id': '9weshe8z', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 3}, 'lr': {'value': 0.006272310529834396}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NTM2Nw==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjl3ZXNoZTh6OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=3': '--lambd=3'
2023-07-01 18:46:30 INFO Running runs: []
2023-07-01 18:46:31 INFO Agent received command: run
2023-07-01 18:46:31 INFO Agent starting run with config:
	lambd: 1
	lr: 0.004170803025021038
2023-07-01 18:46:31 INFO About to run command: --lambd=1 --lr=0.004170803025021038 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:46:31 ERROR Exception while processing command: {'run_id': 'lircodoo', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.004170803025021038}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NTkxNA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmxpcmNvZG9vOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:47:12 INFO Agent received command: run
2023-07-01 18:47:12 INFO Agent starting run with config:
	lambd: 1
	lr: 0.009299238268146517
2023-07-01 18:47:12 INFO About to run command: --lambd=1 --lr=0.009299238268146517 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:47:12 ERROR Exception while processing command: {'run_id': 'psi349zy', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.009299238268146517}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NTkzNQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOnBzaTM0OXp5OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:47:17 INFO Agent received command: run
2023-07-01 18:47:17 INFO Agent starting run with config:
	lambd: 1
	lr: 0.00950476927212558
2023-07-01 18:47:17 INFO About to run command: --lambd=1 --lr=0.00950476927212558 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:47:17 ERROR Exception while processing command: {'run_id': 'ib4trw7y', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.00950476927212558}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NTkzOQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmliNHRydzd5OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:47:23 INFO Agent received command: run
2023-07-01 18:47:23 INFO Agent starting run with config:
	lambd: 1
	lr: 0.007958270487459219
2023-07-01 18:47:23 INFO About to run command: --lambd=1 --lr=0.007958270487459219 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:47:23 ERROR Exception while processing command: {'run_id': 'oboumsj5', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.007958270487459219}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NTk3OQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm9ib3Vtc2o1OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 18:49:32 INFO Running runs: []
2023-07-01 18:49:32 INFO Agent received command: run
2023-07-01 18:49:32 INFO Agent starting run with config:
	lr: 0.004170803025021038
2023-07-01 18:49:32 INFO About to run command: --lr=0.004170803025021038 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:49:32 ERROR Exception while processing command: {'run_id': 'rl1762yu', 'program': 'main.py', 'type': 'run', 'args': {'lr': {'value': 0.004170803025021038}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NjUzNg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOnJsMTc2Mnl1OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lr=0.004170803025021038': '--lr=0.004170803025021038'
2023-07-01 18:49:37 INFO Agent received command: run
2023-07-01 18:49:37 INFO Agent starting run with config:
	lr: 0.004828259366415464
2023-07-01 18:49:37 INFO About to run command: --lr=0.004828259366415464 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 18:49:37 ERROR Exception while processing command: {'run_id': 'mlg2pwli', 'program': 'main.py', 'type': 'run', 'args': {'lr': {'value': 0.004828259366415464}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY4NzU3MA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm1sZzJwd2xpOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lr=0.004828259366415464': '--lr=0.004828259366415464'
2023-07-01 19:03:21 INFO Running runs: []
2023-07-01 19:03:21 INFO Agent received command: run
2023-07-01 19:03:21 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0072035246099281395
2023-07-01 19:03:21 INFO About to run command: --lambd=1 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:21 ERROR Exception while processing command: {'run_id': 't5dr0xa9', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5MzU1Mg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOnQ1ZHIweGE5OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 19:03:27 INFO Agent received command: run
2023-07-01 19:03:27 INFO Agent starting run with config:
	lambd: 0.01
	lr: 0.008260163031459515
2023-07-01 19:03:27 INFO About to run command: --lambd=0.01 --lr=0.008260163031459515 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:27 ERROR Exception while processing command: {'run_id': 'dkaxagxw', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 0.01}, 'lr': {'value': 0.008260163031459515}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5MzU5OA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmRrYXhhZ3h3OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=0.01': '--lambd=0.01'
2023-07-01 19:03:32 INFO Agent received command: run
2023-07-01 19:03:32 INFO Agent starting run with config:
	lambd: 5
	lr: 0.0018670272107962171
2023-07-01 19:03:32 INFO About to run command: --lambd=5 --lr=0.0018670272107962171 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:32 ERROR Exception while processing command: {'run_id': 'ncnscco5', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 5}, 'lr': {'value': 0.0018670272107962171}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5MzYwNw==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm5jbnNjY281OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=5': '--lambd=5'
2023-07-01 19:03:38 INFO Agent received command: run
2023-07-01 19:03:38 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0010755722478437938
2023-07-01 19:03:38 INFO About to run command: --lambd=1 --lr=0.0010755722478437938 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:38 ERROR Exception while processing command: {'run_id': 'vvddpmew', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0010755722478437938}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5MzYxMg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOnZ2ZGRwbWV3OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 19:03:43 INFO Agent received command: run
2023-07-01 19:03:43 INFO Agent starting run with config:
	lambd: 3
	lr: 0.0021177947825025724
2023-07-01 19:03:43 INFO About to run command: --lambd=3 --lr=0.0021177947825025724 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:43 ERROR Exception while processing command: {'run_id': '4myupulj', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 3}, 'lr': {'value': 0.0021177947825025724}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5MzYxNg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOjRteXVwdWxqOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=3': '--lambd=3'
2023-07-01 19:03:49 INFO Agent received command: run
2023-07-01 19:03:49 INFO Agent starting run with config:
	lambd: 0.1
	lr: 0.0034672723901614834
2023-07-01 19:03:49 INFO About to run command: --lambd=0.1 --lr=0.0034672723901614834 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:49 ERROR Exception while processing command: {'run_id': 'daqjjhy4', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 0.1}, 'lr': {'value': 0.0034672723901614834}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDEyMg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmRhcWpqaHk0OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=0.1': '--lambd=0.1'
2023-07-01 19:03:54 INFO Agent received command: run
2023-07-01 19:03:54 INFO Agent starting run with config:
	lambd: 1
	lr: 0.007320635813643522
2023-07-01 19:03:54 INFO About to run command: --lambd=1 --lr=0.007320635813643522 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:03:54 ERROR Exception while processing command: {'run_id': 'khxeka8b', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.007320635813643522}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDEyOA==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmtoeGVrYThiOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1': '--lambd=1'
2023-07-01 19:04:00 INFO Agent received command: run
2023-07-01 19:04:00 INFO Agent starting run with config:
	lambd: 3
	lr: 0.0008610690796219543
2023-07-01 19:04:00 INFO About to run command: --lambd=3 --lr=0.0008610690796219543 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:04:00 ERROR Exception while processing command: {'run_id': 'avvep1h4', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 3}, 'lr': {'value': 0.0008610690796219543}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDEzMg==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmF2dmVwMWg0OkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=3': '--lambd=3'
2023-07-01 19:04:05 INFO Agent received command: run
2023-07-01 19:04:05 INFO Agent starting run with config:
	lambd: 0.1
	lr: 0.009147421712995308
2023-07-01 19:04:05 INFO About to run command: --lambd=0.1 --lr=0.009147421712995308 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:04:05 ERROR Exception while processing command: {'run_id': 'x439guig', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 0.1}, 'lr': {'value': 0.009147421712995308}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDEzNw==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOng0MzlndWlnOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=0.1': '--lambd=0.1'
2023-07-01 19:04:11 INFO Agent received command: run
2023-07-01 19:04:11 INFO Agent starting run with config:
	lambd: 3
	lr: 0.009830994117327014
2023-07-01 19:04:11 INFO About to run command: --lambd=3 --lr=0.009830994117327014 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:04:11 ERROR Exception while processing command: {'run_id': 'axyin3wi', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 3}, 'lr': {'value': 0.009830994117327014}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDE0NQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmF4eWluM3dpOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=3': '--lambd=3'
2023-07-01 19:04:16 INFO Agent received command: run
2023-07-01 19:04:16 INFO Agent starting run with config:
	lambd: 5
	lr: 0.002069675108920525
2023-07-01 19:04:16 INFO About to run command: --lambd=5 --lr=0.002069675108920525 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-01 19:04:16 ERROR Exception while processing command: {'run_id': 'mkkzehfj', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 5}, 'lr': {'value': 0.002069675108920525}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODY5NDE0OQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm1ra3plaGZqOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data1/deepdog/anaconda3/envs/mcl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=5': '--lambd=5'
2023-07-02 04:47:03 INFO Running runs: []
2023-07-02 04:47:04 INFO Agent received command: run
2023-07-02 04:47:04 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0072035246099281395
2023-07-02 04:47:04 INFO About to run command: --lambd=1 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-02 04:47:04 ERROR Exception while processing command: {'run_id': 'kld6lyv1', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODkwNjgyNw==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOmtsZDZseXYxOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1'
2023-07-02 04:49:32 INFO Running runs: []
2023-07-02 04:49:32 INFO Agent received command: run
2023-07-02 04:49:32 INFO Agent starting run with config:
	lambd: 1
	lr: 0.0072035246099281395
2023-07-02 04:49:32 INFO About to run command: --lambd=1 --lr=0.0072035246099281395 --gfml --dataset=amazon-digital-music --gpu_id=1
2023-07-02 04:49:33 ERROR Exception while processing command: {'run_id': 'ov1usaen', 'program': 'main.py', 'type': 'run', 'args': {'lambd': {'value': 1}, 'lr': {'value': 0.0072035246099281395}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjM3ODkwNzQ3NQ==', 'logs': ['expected_improvement: nan', 'predicted_value: 0.0', 'predicted_value_std_dev: nan', 'success_probability: 1.0', 'warnings: \nSweep has no valid samples of the metric.'], 'run_storage_id': 'UnVuOnYxOm92MXVzYWVuOkdGTUxfUmV2aXNpb25fTUNMOmhveW9vbg=='}
Traceback (most recent call last):
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/site-packages/wandb/wandb_agent.py", line 46, in __init__
    self._popen = subprocess.Popen(command, env=env, **kwargs)
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data1/deepdog/anaconda3/envs/gfml/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--lambd=1'
2023-07-04 12:09:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:10:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:10:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:11:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:11:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:12:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:12:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:13:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:13:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:14:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:14:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:15:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:15:34 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:16:04 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
2023-07-04 12:16:36 ERROR dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/hoyoon/GFML_Revision_MCL/1uz9agi6/file_stream
NoneType: None
